#!/bin/bash
if [ "$1" != "" ]; then
    rostopic echo -p /ardrone/imu > `rospack find ardrone_control`/bagfiles/"$1"_$(date +%Y-%m-%d-%H-%M-%S)_imu.csv
else
    rostopic echo -p /ardrone/imu > `rospack find ardrone_control`/bagfiles/$(date +%Y-%m-%d-%H-%M-%S)_imu.csv
fi

