#!/bin/bash
if [ "$1" != "" ]; then
    rostopic echo -p /ardrone/navdata > `rospack find ardrone_control`/bagfiles/"$1"_$(date +%Y-%m-%d-%H-%M-%S)_navdata.csv
else
    rostopic echo -p /ardrone/navdata > `rospack find ardrone_control`/bagfiles/$(date +%Y-%m-%d-%H-%M-%S)_navdata.csv
fi